In [1]:
import pandas as pd
import torch
import os
import matplotlib.pyplot as plt
import numpy as np

In [2]:
DATA_DIR = "../data"

bars_seen_train         = pd.read_parquet(os.path.join(DATA_DIR, "bars_seen_train.parquet"), engine="fastparquet")
bars_unseen_train       = pd.read_parquet(os.path.join(DATA_DIR, "bars_unseen_train.parquet"), engine="fastparquet")
bars_seen_public_test   = pd.read_parquet(os.path.join(DATA_DIR, "bars_seen_public_test.parquet"), engine="fastparquet")
bars_seen_private_test  = pd.read_parquet(os.path.join(DATA_DIR, "bars_seen_private_test.parquet"), engine="fastparquet")

headlines_seen_train        = pd.read_parquet(os.path.join(DATA_DIR, "headlines_seen_train.parquet"), engine="fastparquet")
headlines_unseen_train      = pd.read_parquet(os.path.join(DATA_DIR, "headlines_unseen_train.parquet"), engine="fastparquet")
headlines_seen_public_test  = pd.read_parquet(os.path.join(DATA_DIR, "headlines_seen_public_test.parquet"), engine="fastparquet")
headlines_seen_private_test = pd.read_parquet(os.path.join(DATA_DIR, "headlines_seen_private_test.parquet"), engine="fastparquet")

print("bars_seen_train:",         bars_seen_train.shape)
print("bars_unseen_train:",       bars_unseen_train.shape)
print("bars_seen_public_test:",   bars_seen_public_test.shape)
print("bars_seen_private_test:",  bars_seen_private_test.shape)
print("headlines_seen_train:",        headlines_seen_train.shape)
print("headlines_unseen_train:",      headlines_unseen_train.shape)
print("headlines_seen_public_test:",  headlines_seen_public_test.shape)
print("headlines_seen_private_test:", headlines_seen_private_test.shape)

bars_seen_train: (50000, 6)
bars_unseen_train: (50000, 6)
bars_seen_public_test: (500000, 6)
bars_seen_private_test: (500000, 6)
headlines_seen_train: (9740, 3)
headlines_unseen_train: (7631, 3)
headlines_seen_public_test: (99308, 3)
headlines_seen_private_test: (99148, 3)

In [3]:
def build_company_session_logs(df):
    df['company'] = df['headline'].str.split().str[:2].str.join(' ')
    # Group by session and company, then aggregate headlines into a list
    grouped_list_df = df.groupby(['session', 'company'])['headline'].apply(list).reset_index()

    # Rename the column for clarity
    grouped_list_df.rename(columns={'headline': 'all_headlines'}, inplace=True)
    
    return grouped_list_df

In [4]:
headlines_per_company_session = build_company_session_logs(headlines_seen_train)

In [5]:
headlines_per_company_session.head(10)

,session,company,all_headlines
0,0,Calvis Sciences,[Calvis Sciences secures $650M contract with a...
1,0,Orevex Renewables,[Orevex Renewables secures $500M contract with...
2,0,Relvos Biosciences,[Relvos Biosciences opens new office in Southe...
3,0,Yorvov Pharmaceuticals,[Yorvov Pharmaceuticals secures $180M contract...
4,1,Halvav Brands,[Halvav Brands sees mixed results in wireless ...
5,1,Jorvis Fuels,[Jorvis Fuels reports record quarterly revenue...
6,1,Strynal Industries,[Strynal Industries reports 15% decline in ope...
7,1,Zrovex Industries,[Zrovex Industries loses key contract in Asia ...
8,2,Kelvik Power,[Kelvik Power secures $800M contract with a le...
9,2,Zelval Energy,[Zelval Energy to host investor day focused on...

In [6]:
# Print the first 10 companies and their event sequences
print("--- Sample of Event Sequences ---")

for index, row in headlines_per_company_session.head(10).iterrows():
    # .ljust(25) adds spaces so the arrows all line up perfectly
    company_name = row['company'].ljust(25)
    sequence = row['all_headlines']
    
    print(f"Session {row['session']} | {company_name} -> {sequence}")

--- Sample of Event Sequences ---
Session 0 | Calvis Sciences           -> ['Calvis Sciences secures $650M contract with a leading cloud platform', 'Calvis Sciences expands operations into Asia Pacific markets']
Session 0 | Orevex Renewables         -> ['Orevex Renewables secures $500M contract with a global retailer', 'Orevex Renewables secures $650M contract with a major logistics provider', 'Orevex Renewables faces class action over automated logistics service disruption']
Session 0 | Relvos Biosciences        -> ['Relvos Biosciences opens new office in Southeast Asia', 'Relvos Biosciences names new head of precision manufacturing division', 'Relvos Biosciences reports 3% decline in operating income', 'Relvos Biosciences secures $320M contract with a leading cloud platform']
Session 0 | Yorvov Pharmaceuticals    -> ['Yorvov Pharmaceuticals secures $180M contract with a national infrastructure agency', 'Yorvov Pharmaceuticals sees mixed results in supply chain optimization pilot program']
Session 1 | Halvav Brands             -> ['Halvav Brands sees mixed results in wireless connectivity pilot program', 'Halvav Brands reports rising costs pressuring margins in digital payments']
Session 1 | Jorvis Fuels              -> ['Jorvis Fuels reports record quarterly revenue, up 12% year-over-year', 'Jorvis Fuels secures $400M contract with an international consortium', 'Jorvis Fuels sees 12% margin improvement in latest quarter', 'Jorvis Fuels secures $75M contract with a multinational manufacturer', 'Jorvis Fuels names new head of process automation division', 'Jorvis Fuels recalls products in digital payments line due to quality concerns']
Session 1 | Strynal Industries        -> ['Strynal Industries reports 15% decline in operating income', 'Strynal Industries reports 20% increase in customer acquisition']
Session 1 | Zrovex Industries         -> ['Zrovex Industries loses key contract in Asia Pacific to competitor', 'Zrovex Industries reports strong demand in Latin America, raises outlook', 'Zrovex Industries completes strategic acquisition to strengthen data analytics', 'Zrovex Industries faces class action over digital payments service disruption', 'Zrovex Industries reports rising costs pressuring margins in automated logistics', 'Zrovex Industries sees 25% drop in new customer orders this quarter']
Session 2 | Kelvik Power              -> ['Kelvik Power secures $800M contract with a leading cloud platform', 'Kelvik Power withdraws from Scandinavia market citing unfavorable conditions', 'Kelvik Power secures $800M contract with a national infrastructure agency', 'Kelvik Power launches next-generation wireless connectivity platform', 'Kelvik Power recalls products in renewable storage line due to quality concerns', 'Kelvik Power misses quarterly revenue estimates by 15%']
Session 2 | Zelval Energy             -> ['Zelval Energy to host investor day focused on digital payments strategy', 'Zelval Energy misses quarterly revenue estimates by 10%']

In [7]:
def replace_headlines_with_keywords(headlines):
    new_headlines = []
    magic_words = [ "secures",
                    "expands",
                    "decline in operating income",
                    "improvement",
                    "opens",
                    "class action",
                    "loses key contract",
                    "withdraws",
                    "launches",
                    "recalls",
                    "misses",
                    "buyback program",
                    "droped",
                    "rising costs",
                    "mixed results",
                    "drop",
                    "breakthrough",
                    "acquisition",
                    "new head",
                    "strong demand",
                    "capital expenditure",
                    "scheduled maintenance",
                    "disruptions",
                    "excellence",
                    "facility upgrade",
                    "record quarterly revenue",
                    "explores strategic alternatives",
                    "routine patent applications",
                    "regulatory review",
                    "delays product launch",
                    "restructuring",
                    "revises long-term strategy",
                    "regulatory milestone",
                    "regulatory approval",
                    "host investor day",
                    "addresses investor concerns",
                    "confirms participation",
                    "enters joint venture",
                    "signs multi-year partnership",
                    "steps down unexpectedly",
                    "present at",
                    "lowers full-year guidance",
                    "publishes annual",
                    "schedules annual shareholder",
                    "major strategic initiative",
                    "potential merger",
                    "beats analyst expectations",
                    "raises full-year guidance",
                    "reports unexpected decline in"]
    
    ambiguous_headlines = []
    for headline in headlines:
        matches = 0
        for word in magic_words:
            if word in headline.lower():
                new_headlines.append(word)
                matches += 1
        if matches == 0:
            new_headlines.append(headline)    
        if matches > 1:
            ambiguous_headlines.append(headline)
            
    if len(ambiguous_headlines) != 0:
        print(f"Ambigous headlines:{ambiguous_headlines}")
    
    return new_headlines

In [8]:
headlines_per_company_session['encoded_keywords'] = headlines_per_company_session['all_headlines'].apply(replace_headlines_with_keywords)

In [9]:
master_long_headlines = []

# Assuming the column with the lists of text is named 'all_headlines'
for headline_list in headlines_per_company_session['encoded_keywords']:
    for text in headline_list:
        # Check if the text has more than 1 word
        if len(str(text).split()) > 4:
            master_long_headlines.append(text)

print(len(master_long_headlines))
for long_head in master_long_headlines:
    print(long_head) # Preview the first 5

0

In [10]:
unique_tuples = headlines_per_company_session['encoded_keywords'].apply(tuple).unique()

# 2. Convert them back to lists for easy reading
all_unique_patterns = [list(pattern) for pattern in unique_tuples]

print(f"Total unique patterns found: {len(all_unique_patterns)}\n")

# Print them all out
for pattern in all_unique_patterns:
    print(pattern)

Total unique patterns found: 2458

['secures', 'expands']
['secures', 'secures', 'class action']
['opens', 'new head', 'decline in operating income', 'secures']
['secures', 'mixed results']
['mixed results', 'rising costs']
['record quarterly revenue', 'secures', 'improvement', 'secures', 'new head', 'recalls']
['decline in operating income', 'acquisition']
['loses key contract', 'strong demand', 'acquisition', 'class action', 'rising costs', 'drop']
['secures', 'withdraws', 'secures', 'launches', 'recalls', 'misses']
['host investor day', 'misses']
['withdraws', 'scheduled maintenance']
['explores strategic alternatives', 'secures', 'strong demand']
['facility upgrade', 'steps down unexpectedly', 'routine patent applications', 'loses key contract']
['drop', 'revises long-term strategy']
['withdraws', 'acquisition']
['new head', 'buyback program']
['secures', 'launches']
['decline in operating income', 'buyback program', 'routine patent applications', 'record quarterly revenue']
['drop']
['new head']
['capital expenditure', 'delays product launch']
['secures', 'facility upgrade', 'schedules annual shareholder']
['capital expenditure', 'acquisition', 'class action']
['regulatory review', 'secures', 'secures']
['acquisition']
['confirms participation', 'secures', 'rising costs']
['improvement', 'scheduled maintenance', 'record quarterly revenue', 'recalls', 'expands']
['routine patent applications']
['improvement', 'capital expenditure', 'explores strategic alternatives', 'disruptions']
['strong demand', 'launches', 'secures']
['mixed results']
['drop', 'excellence', 'misses', 'secures', 'rising costs']
['scheduled maintenance', 'disruptions']
['scheduled maintenance', 'loses key contract', 'new head', 'disruptions']
['routine patent applications', 'new head', 'launches']
['restructuring', 'delays product launch', 'facility upgrade', 'routine patent applications', 'secures']
['regulatory approval', 'secures']
['secures', 'host investor day', 'misses']
['explores strategic alternatives', 'recalls', 'acquisition']
['regulatory review']
['revises long-term strategy']
['steps down unexpectedly']
['class action', 'delays product launch', 'acquisition', 'excellence']
['secures', 'regulatory approval', 'expands', 'acquisition', 'secures', 'revises long-term strategy', 'explores strategic alternatives']
['loses key contract', 'record quarterly revenue']
['host investor day', 'misses', 'secures', 'secures']
['breakthrough', 'excellence']
['addresses investor concerns']
['host investor day', 'explores strategic alternatives']
['mixed results', 'secures', 'misses', 'loses key contract', 'capital expenditure']
['secures', 'reports unexpected decline in', 'secures']
['explores strategic alternatives']
['secures', 'secures', 'regulatory approval']
['excellence']
['revises long-term strategy', 'acquisition', 'improvement']
['expands', 'secures', 'addresses investor concerns']
['opens', 'launches']
['revises long-term strategy', 'routine patent applications', 'excellence']
['secures', 'decline in operating income', 'secures', 'revises long-term strategy', 'explores strategic alternatives']
['regulatory approval', 'scheduled maintenance']
['routine patent applications', 'recalls']
['breakthrough']
['loses key contract']
['regulatory milestone', 'class action']
['mixed results', 'new head']
['delays product launch']
['recalls', 'explores strategic alternatives']
['disruptions', 'acquisition', 'explores strategic alternatives', 'regulatory approval']
['expands', 'secures']
['acquisition', 'host investor day', 'opens']
['withdraws', 'withdraws', 'explores strategic alternatives', 'secures']
['new head', 'opens', 'secures', 'acquisition']
['excellence', 'secures', 'secures', 'record quarterly revenue']
['misses', 'secures', 'launches', 'new head']
['recalls']
['expands']
['explores strategic alternatives', 'regulatory approval']
['host investor day', 'loses key contract', 'acquisition', 'breakthrough', 'buyback program', 'strong demand']
['routine patent applications', 'buyback program', 'decline in operating income', 'lowers full-year guidance', 'secures']
['reports unexpected decline in']
['acquisition', 'scheduled maintenance', 'confirms participation']
['secures', 'secures']
['new head', 'explores strategic alternatives', 'scheduled maintenance', 'new head']
['delays product launch', 'regulatory review']
['secures', 'improvement', 'secures']
['explores strategic alternatives', 'record quarterly revenue', 'explores strategic alternatives', 'breakthrough', 'explores strategic alternatives', 'secures']
['host investor day', 'recalls']
['acquisition', 'new head', 'delays product launch', 'steps down unexpectedly']
['facility upgrade', 'improvement', 'withdraws']
['secures', 'decline in operating income', 'secures', 'secures']
['buyback program', 'facility upgrade', 'routine patent applications', 'secures', 'regulatory approval']
['excellence', 'secures', 'routine patent applications', 'regulatory review']
['beats analyst expectations', 'improvement']
['confirms participation', 'acquisition', 'secures', 'regulatory review', 'misses', 'facility upgrade', 'mixed results']
['secures']
['record quarterly revenue', 'host investor day']
['acquisition', 'secures']
['regulatory approval', 'strong demand', 'steps down unexpectedly', 'secures']
['enters joint venture', 'secures', 'decline in operating income', 'secures']
['secures', 'secures', 'scheduled maintenance', 'breakthrough']
['scheduled maintenance']
['rising costs', 'acquisition', 'explores strategic alternatives']
['enters joint venture', 'scheduled maintenance']
['secures', 'strong demand']
['signs multi-year partnership', 'regulatory approval']
['secures', 'misses', 'regulatory approval']
['expands', 'loses key contract', 'withdraws']
['decline in operating income', 'mixed results', 'reports unexpected decline in', 'secures']
['rising costs', 'improvement', 'secures']
['secures', 'host investor day']
['record quarterly revenue', 'excellence']
['secures', 'addresses investor concerns']
['host investor day']
['acquisition', 'secures', 'scheduled maintenance', 'recalls']
['confirms participation', 'explores strategic alternatives', 'explores strategic alternatives']
['revises long-term strategy', 'breakthrough']
['signs multi-year partnership']
['breakthrough', 'drop']
['misses']
['decline in operating income']
['class action', 'facility upgrade', 'new head']
['secures', 'delays product launch']
['secures', 'routine patent applications']
['acquisition', 'withdraws']
['secures', 'excellence', 'acquisition', 'secures', 'launches']
['class action']
['routine patent applications', 'misses']
['facility upgrade', 'secures']
['acquisition', 'launches', 'launches']
['secures', 'misses', 'secures']
['mixed results', 'launches']
['improvement', 'withdraws']
['confirms participation', 'addresses investor concerns']
['present at']
['record quarterly revenue', 'facility upgrade', 'routine patent applications']
['drop', 'secures']
['new head', 'withdraws', 'regulatory approval']
['delays product launch', 'reports unexpected decline in']
['excellence', 'decline in operating income', 'regulatory approval', 'explores strategic alternatives']
['steps down unexpectedly', 'routine patent applications']
['acquisition', 'secures', 'drop', 'expands', 'revises long-term strategy']
['recalls', 'delays product launch']
['drop', 'buyback program', 'routine patent applications', 'secures']
['secures', 'secures', 'rising costs', 'decline in operating income']
['scheduled maintenance', 'present at']
['secures', 'rising costs']
['lowers full-year guidance', 'secures']
['buyback program', 'capital expenditure', 'withdraws']
['drop', 'routine patent applications', 'revises long-term strategy']
['delays product launch', 'secures', 'lowers full-year guidance']
['secures', 'secures', 'capital expenditure']
['recalls', 'host investor day', 'decline in operating income', 'acquisition', 'revises long-term strategy']
['buyback program']
['loses key contract', 'regulatory review', 'regulatory review']
['routine patent applications', 'secures', 'launches']
['new head', 'misses', 'scheduled maintenance', 'launches']
['revises long-term strategy', 'improvement', 'disruptions']
['host investor day', 'host investor day', 'restructuring', 'restructuring', 'secures', 'acquisition']
['signs multi-year partnership', 'buyback program', 'new head']
['present at', 'rising costs']
['decline in operating income', 'drop']
['enters joint venture', 'decline in operating income', 'secures']
['buyback program', 'launches']
['host investor day', 'class action']
['addresses investor concerns', 'class action', 'capital expenditure', 'loses key contract']
['secures', 'secures', 'routine patent applications', 'opens', 'acquisition']
['secures', 'excellence']
['drop', 'launches', 'scheduled maintenance', 'withdraws', 'secures']
['strong demand', 'decline in operating income']
['delays product launch', 'enters joint venture']
['class action', 'strong demand', 'new head', 'addresses investor concerns', 'enters joint venture', 'opens']
['breakthrough', 'revises long-term strategy']
['steps down unexpectedly', 'scheduled maintenance', 'facility upgrade']
['strong demand', 'strong demand', 'confirms participation']
['loses key contract', 'present at', 'addresses investor concerns', 'excellence']
['secures', 'misses', 'signs multi-year partnership']
['class action', 'confirms participation']
['expands', 'secures', 'mixed results']
['mixed results', 'secures', 'mixed results', 'host investor day', 'secures', 'signs multi-year partnership']
['record quarterly revenue', 'excellence', 'confirms participation']
['addresses investor concerns', 'facility upgrade']
['breakthrough', 'secures', 'routine patent applications', 'host investor day', 'secures']
['decline in operating income', 'capital expenditure', 'record quarterly revenue', 'recalls']
['explores strategic alternatives', 'regulatory review']
['buyback program', 'mixed results', 'capital expenditure']
['scheduled maintenance', 'decline in operating income', 'scheduled maintenance']
['publishes annual']
['recalls', 'disruptions']
['class action', 'delays product launch', 'acquisition', 'revises long-term strategy', 'excellence', 'decline in operating income', 'launches']
['present at', 'opens', 'expands', 'regulatory approval']
['host investor day', 'scheduled maintenance', 'strong demand', 'excellence']
['host investor day', 'mixed results', 'regulatory approval']
['launches', 'secures', 'disruptions']
['enters joint venture', 'secures', 'improvement', 'launches', 'improvement']
['scheduled maintenance', 'secures', 'improvement']
['launches']
['secures', 'secures', 'launches']
['new head', 'secures', 'record quarterly revenue']
['withdraws', 'record quarterly revenue', 'record quarterly revenue', 'improvement']
['facility upgrade', 'misses', 'regulatory review']
['strong demand']
['host investor day', 'expands']
['misses', 'misses', 'beats analyst expectations', 'withdraws']
['delays product launch', 'enters joint venture', 'excellence']
['rising costs']
['lowers full-year guidance', 'launches', 'recalls']
['restructuring']
['excellence', 'steps down unexpectedly', 'acquisition', 'revises long-term strategy']
['facility upgrade']
['secures', 'addresses investor concerns', 'revises long-term strategy']
['secures', 'secures', 'secures', 'decline in operating income']
['revises long-term strategy', 'host investor day', 'secures', 'misses']
['new head', 'facility upgrade']
['present at', 'class action']
['secures', 'regulatory review', 'host investor day', 'withdraws']
['rising costs', 'secures', 'secures']
['loses key contract', 'capital expenditure', 'capital expenditure', 'secures', 'explores strategic alternatives']
['new head', 'class action', 'acquisition']
['secures', 'excellence', 'secures', 'revises long-term strategy']
['excellence', 'capital expenditure']
['secures', 'new head']
['record quarterly revenue', 'regulatory review']
['launches', 'secures', 'record quarterly revenue', 'explores strategic alternatives', 'opens', 'class action']
['launches', 'capital expenditure']
['secures', 'drop', 'routine patent applications']
['excellence', 'secures']
['new head', 'buyback program', 'secures', 'scheduled maintenance', 'capital expenditure']
['regulatory approval', 'loses key contract', 'loses key contract']
['signs multi-year partnership', 'explores strategic alternatives', 'class action']
['acquisition', 'revises long-term strategy', 'secures']
['breakthrough', 'decline in operating income']
['record quarterly revenue', 'explores strategic alternatives', 'record quarterly revenue']
['secures', 'rising costs', 'secures', 'signs multi-year partnership']
['explores strategic alternatives', 'misses']
['facility upgrade', 'withdraws', 'routine patent applications', 'secures', 'secures', 'class action']
['mixed results', 'secures']
['acquisition', 'secures', 'misses', 'explores strategic alternatives', 'decline in operating income']
['secures', 'facility upgrade']
['regulatory review', 'launches']
['secures', 'addresses investor concerns', 'misses', 'misses']
['regulatory approval']
['addresses investor concerns', 'secures', 'capital expenditure', 'class action', 'secures']
['rising costs', 'explores strategic alternatives']
['strong demand', 'improvement', 'record quarterly revenue']
['opens', 'drop', 'acquisition']
['new head', 'explores strategic alternatives']
['recalls', 'secures', 'drop']
['improvement', 'rising costs', 'regulatory approval']
['opens', 'opens']
['explores strategic alternatives', 'signs multi-year partnership', 'scheduled maintenance', 'explores strategic alternatives', 'secures', 'withdraws']
['buyback program', 'breakthrough']
['launches', 'routine patent applications']
['reports unexpected decline in', 'launches', 'decline in operating income', 'secures']
['signs multi-year partnership', 'decline in operating income', 'mixed results', 'explores strategic alternatives', 'routine patent applications']
['opens', 'routine patent applications', 'acquisition']
['signs multi-year partnership', 'facility upgrade', 'excellence']
['breakthrough', 'secures']
['scheduled maintenance', 'acquisition', 'secures', 'routine patent applications']
['regulatory review', 'scheduled maintenance', 'rising costs', 'regulatory milestone']
['class action', 'capital expenditure']
['class action', 'secures']
['capital expenditure', 'acquisition']
['explores strategic alternatives', 'secures', 'revises long-term strategy', 'mixed results']
['delays product launch', 'secures']
['misses', 'capital expenditure']
['steps down unexpectedly', 'breakthrough']
['recalls', 'class action', 'secures', 'improvement', 'explores strategic alternatives']
['secures', 'recalls', 'revises long-term strategy']
['explores strategic alternatives', 'secures']
['excellence', 'facility upgrade', 'reports unexpected decline in']
['acquisition', 'drop', 'misses', 'acquisition']
['mixed results', 'improvement', 'improvement']
['secures', 'record quarterly revenue', 'rising costs']
['enters joint venture', 'routine patent applications']
['opens']
['acquisition', 'steps down unexpectedly', 'regulatory milestone', 'revises long-term strategy']
['secures', 'new head', 'explores strategic alternatives']
['enters joint venture', 'improvement', 'secures']
['scheduled maintenance', 'routine patent applications']
['recalls', 'capital expenditure', 'steps down unexpectedly', 'recalls', 'new head', 'record quarterly revenue', 'host investor day', 'revises long-term strategy']
['withdraws', 'rising costs', 'explores strategic alternatives', 'secures']
['improvement', 'record quarterly revenue']
['disruptions', 'confirms participation', 'delays product launch', 'acquisition']
['secures', 'facility upgrade', 'withdraws', 'host investor day', 'misses']
['regulatory review', 'routine patent applications', 'revises long-term strategy']
['facility upgrade', 'explores strategic alternatives', 'launches', 'reports unexpected decline in']
['delays product launch', 'secures', 'disruptions', 'reports unexpected decline in']
['record quarterly revenue', 'enters joint venture', 'facility upgrade']
['secures', 'drop', 'drop']
['loses key contract', 'publishes annual', 'secures', 'host investor day']
['explores strategic alternatives', 'secures', 'secures', 'drop', 'secures']
['opens', 'confirms participation', 'mixed results']
['host investor day', 'acquisition']
['host investor day', 'withdraws']
['addresses investor concerns', 'secures']
['explores strategic alternatives', 'new head']
['regulatory review', 'buyback program']
['buyback program', 'regulatory review', 'new head', 'secures', 'rising costs']
['confirms participation', 'delays product launch', 'acquisition']
['acquisition', 'secures', 'misses']
['breakthrough', 'enters joint venture', 'schedules annual shareholder']
['revises long-term strategy', 'loses key contract', 'confirms participation']
['secures', 'regulatory approval']
['reports unexpected decline in', 'explores strategic alternatives', 'decline in operating income', 'reports unexpected decline in']
['secures', 'acquisition', 'excellence']
['confirms participation']
['reports unexpected decline in', 'loses key contract']
['buyback program', 'delays product launch']
['secures', 'explores strategic alternatives']
['regulatory approval', 'enters joint venture']
['explores strategic alternatives', 'secures', 'enters joint venture', 'secures', 'secures', 'restructuring', 'withdraws']
['record quarterly revenue', 'revises long-term strategy', 'secures']
['secures', 'scheduled maintenance']
['secures', 'present at', 'secures', 'disruptions', 'withdraws', 'routine patent applications', 'mixed results']
['explores strategic alternatives', 'record quarterly revenue', 'buyback program']
['acquisition', 'recalls']
['secures', 'expands', 'restructuring']
['buyback program', 'facility upgrade', 'revises long-term strategy', 'buyback program']
['host investor day', 'regulatory review', 'facility upgrade', 'delays product launch']
['strong demand', 'improvement']
['explores strategic alternatives', 'scheduled maintenance']
['misses', 'record quarterly revenue', 'enters joint venture']
['secures', 'facility upgrade', 'reports unexpected decline in']
['explores strategic alternatives', 'raises full-year guidance', 'regulatory review']
['buyback program', 'acquisition']
['regulatory review', 'rising costs', 'acquisition']
['raises full-year guidance']
['addresses investor concerns', 'revises long-term strategy', 'record quarterly revenue', 'secures', 'potential merger']
['class action', 'host investor day']
['rising costs', 'present at']
['record quarterly revenue', 'acquisition']
['secures', 'secures', 'withdraws', 'new head']
['delays product launch', 'delays product launch', 'secures']
['major strategic initiative', 'excellence', 'class action', 'misses', 'expands']
['secures', 'secures', 'explores strategic alternatives']
['drop', 'disruptions', 'regulatory review', 'steps down unexpectedly']
['signs multi-year partnership', 'facility upgrade', 'loses key contract']
['capital expenditure', 'new head']
['secures', 'opens', 'expands', 'breakthrough', 'breakthrough']
['loses key contract', 'confirms participation', 'secures']
['present at', 'routine patent applications']
['expands', 'recalls']
['regulatory review', 'rising costs', 'launches', 'expands', 'revises long-term strategy', 'acquisition']
['present at', 'excellence', 'delays product launch']
['misses', 'record quarterly revenue']
['rising costs', 'acquisition', 'secures', 'buyback program']
['regulatory approval', 'drop']
['steps down unexpectedly', 'revises long-term strategy']
['confirms participation', 'secures', 'enters joint venture']
['withdraws', 'delays product launch']
['opens', 'drop', 'secures']
['secures', 'class action']
['strong demand', 'secures']
['signs multi-year partnership', 'regulatory milestone', 'regulatory review', 'revises long-term strategy', 'secures']

In [11]:
frequency_df = headlines_per_company_session['encoded_keywords'].apply(tuple).value_counts().reset_index()
frequency_df.columns = ['encoded_keywords', 'frequency']

# 3. Convert the tuples back to lists for a cleaner look
frequency_df['encoded_keywords'] = frequency_df['encoded_keywords'].apply(list)

In [12]:
frequency_df[frequency_df["frequency"]>5]

                         encoded_keywords  frequency
0                               [secures]        132
1                           [acquisition]         45
2            [revises long-term strategy]         33
3                 [scheduled maintenance]         31
4                         [mixed results]         27
5                     [regulatory review]         24
6                          [class action]         23
7                            [excellence]         23
8                 [delays product launch]         23
9                      [secures, secures]         22
10                         [rising costs]         20
11                               [misses]         20
12                             [launches]         20
13                              [recalls]         20
14                          [disruptions]         20
15                              [expands]         20
16                                 [drop]         20
17                         [breakthrough]         19
18                             [new head]         19
19                    [host investor day]         19
20         [signs multi-year partnership]         18
21          [routine patent applications]         18
22                 [enters joint venture]         18
23      [explores strategic alternatives]         17
24             [record quarterly revenue]         17
25                          [improvement]         16
26                  [regulatory approval]         16
27                        [strong demand]         15
28          [decline in operating income]         14
29                            [withdraws]         14
30                   [loses key contract]         14
31               [confirms participation]         14
32                           [present at]         14
33                      [buyback program]         14
34        [reports unexpected decline in]         13
35                  [capital expenditure]         12
36                                [opens]         12
37                     [facility upgrade]         12
38                 [secures, acquisition]         11
39              [steps down unexpectedly]         10
40                 [acquisition, secures]          8
41               [secures, strong demand]          8
42          [addresses investor concerns]          8
43       [secures, delays product launch]          7
44                        [secures, drop]          6
45  [secures, revises long-term strategy]          6
46                    [new head, secures]          6
47                [secures, rising costs]          6
48                     [secures, recalls]          6

In [13]:
def print_nested_patterns(frequency_df):
    """
    Builds a Prefix Tree from the sequences and prints it hierarchically.
    Assumes frequency_df has columns: ['event_pattern', 'frequency']
    """
    # 1. Build the Tree
    tree = {}
    
    for _, row in frequency_df.iterrows():
        sequence = row['encoded_keywords']
        freq = row['frequency']
        
        # Skip empty sequences
        if not sequence:
            continue
            
        current_node = tree
        for event in sequence:
            if event not in current_node:
                # Initialize the node with a count and an empty dictionary for its children
                current_node[event] = {'_count': 0, 'children': {}}
            
            # Add the frequency to this specific path
            current_node[event]['_count'] += freq
            
            # Move down to the next level
            current_node = current_node[event]['children']

    # 2. Recursive function to print the tree with formatting
    def display_tree(node, prefix=""):
        # Sort the branches at this level by frequency (highest first)
        sorted_branches = sorted(node.items(), key=lambda item: item[1]['_count'], reverse=True)
        
        for i, (event, data) in enumerate(sorted_branches):
            is_last = (i == len(sorted_branches) - 1)
            count = data['_count']
            
            # Choose the correct pipe formatting
            branch_char = "└── " if is_last else "├── "
            
            # Print the current event and its frequency
            print(f"{prefix}{branch_char}[{event}] (Total: {count})")
            
            # Determine the prefix for the children of this event
            next_prefix = prefix + ("    " if is_last else "│   ")
            
            # Recursively print the children
            display_tree(data['children'], next_prefix)

    print("--- Nested Event Sequences ---\n")
    display_tree(tree)

# Execute the function using the frequency dataframe we created earlier
# print_nested_patterns(frequency_df)

In [14]:
print_nested_patterns(frequency_df)

--- Nested Event Sequences ---

├── [secures] (Total: 585)
│   ├── [secures] (Total: 70)
│   │   ├── [secures] (Total: 5)
│   │   │   ├── [decline in operating income] (Total: 1)
│   │   │   └── [regulatory review] (Total: 1)
│   │   ├── [withdraws] (Total: 4)
│   │   │   ├── [capital expenditure] (Total: 1)
│   │   │   │   └── [improvement] (Total: 1)
│   │   │   ├── [new head] (Total: 1)
│   │   │   └── [signs multi-year partnership] (Total: 1)
│   │   │       └── [rising costs] (Total: 1)
│   │   ├── [regulatory review] (Total: 3)
│   │   ├── [scheduled maintenance] (Total: 3)
│   │   │   ├── [decline in operating income] (Total: 1)
│   │   │   │   └── [launches] (Total: 1)
│   │   │   │       └── [new head] (Total: 1)
│   │   │   │           └── [secures] (Total: 1)
│   │   │   └── [breakthrough] (Total: 1)
│   │   ├── [buyback program] (Total: 3)
│   │   │   ├── [host investor day] (Total: 1)
│   │   │   │   └── [reports unexpected decline in] (Total: 1)
│   │   │   └── [new head] (Total: 1)
│   │   ├── [acquisition] (Total: 3)
│   │   │   ├── [regulatory milestone] (Total: 1)
│   │   │   ├── [host investor day] (Total: 1)
│   │   │   └── [secures] (Total: 1)
│   │   ├── [record quarterly revenue] (Total: 2)
│   │   │   └── [scheduled maintenance] (Total: 1)
│   │   │       └── [explores strategic alternatives] (Total: 1)
│   │   ├── [disruptions] (Total: 2)
│   │   │   └── [host investor day] (Total: 1)
│   │   │       └── [excellence] (Total: 1)
│   │   ├── [launches] (Total: 2)
│   │   │   └── [new head] (Total: 1)
│   │   │       └── [breakthrough] (Total: 1)
│   │   │           └── [secures] (Total: 1)
│   │   │               └── [reports unexpected decline in] (Total: 1)
│   │   │                   └── [secures] (Total: 1)
│   │   │                       └── [enters joint venture] (Total: 1)
│   │   ├── [strong demand] (Total: 2)
│   │   │   └── [recalls] (Total: 1)
│   │   ├── [class action] (Total: 2)
│   │   │   └── [reports unexpected decline in] (Total: 1)
│   │   │       └── [secures] (Total: 1)
│   │   ├── [capital expenditure] (Total: 2)
│   │   │   └── [facility upgrade] (Total: 1)
│   │   ├── [signs multi-year partnership] (Total: 1)
│   │   ├── [schedules annual shareholder] (Total: 1)
│   │   ├── [opens] (Total: 1)
│   │   │   └── [secures] (Total: 1)
│   │   │       └── [confirms participation] (Total: 1)
│   │   ├── [regulatory approval] (Total: 1)
│   │   ├── [revises long-term strategy] (Total: 1)
│   │   │   └── [secures] (Total: 1)
│   │   ├── [improvement] (Total: 1)
│   │   ├── [rising costs] (Total: 1)
│   │   │   └── [decline in operating income] (Total: 1)
│   │   ├── [routine patent applications] (Total: 1)
│   │   │   └── [opens] (Total: 1)
│   │   │       └── [acquisition] (Total: 1)
│   │   ├── [explores strategic alternatives] (Total: 1)
│   │   ├── [mixed results] (Total: 1)
│   │   │   └── [addresses investor concerns] (Total: 1)
│   │   ├── [drop] (Total: 1)
│   │   ├── [present at] (Total: 1)
│   │   ├── [reports unexpected decline in] (Total: 1)
│   │   │   └── [recalls] (Total: 1)
│   │   │       └── [signs multi-year partnership] (Total: 1)
│   │   │           └── [present at] (Total: 1)
│   │   ├── [breakthrough] (Total: 1)
│   │   │   └── [routine patent applications] (Total: 1)
│   │   └── [excellence] (Total: 1)
│   │       └── [capital expenditure] (Total: 1)
│   ├── [acquisition] (Total: 25)
│   │   ├── [secures] (Total: 6)
│   │   │   ├── [breakthrough] (Total: 1)
│   │   │   │   └── [new head] (Total: 1)
│   │   │   ├── [scheduled maintenance] (Total: 1)
│   │   │   ├── [present at] (Total: 1)
│   │   │   ├── [secures] (Total: 1)
│   │   │   └── [improvement] (Total: 1)
│   │   │       └── [acquisition] (Total: 1)
│   │   ├── [loses key contract] (Total: 2)
│   │   │   └── [potential merger] (Total: 1)
│   │   ├── [improvement] (Total: 1)
│   │   ├── [scheduled maintenance] (Total: 1)
│   │   │   └── [improvement] (Total: 1)
│   │   ├── [enters joint venture] (Total: 1)
│   │   ├── [host investor day] (Total: 1)
│   │   ├── [excellence] (Total: 1)
│   │   └── [decline in operating income] (Total: 1)
│   │       └── [secures] (Total: 1)
│   ├── [facility upgrade] (Total: 17)
│   │   ├── [secures] (Total: 2)
│   │   │   └── [regulatory approval] (Total: 1)
│   │   │       └── [acquisition] (Total: 1)
│   │   ├── [restructuring] (Total: 1)
│   │   ├── [strong demand] (Total: 1)
│   │   │   └── [scheduled maintenance] (Total: 1)
│   │   ├── [revises long-term strategy] (Total: 1)
│   │   │   └── [confirms participation] (Total: 1)
│   │   │       └── [secures] (Total: 1)
│   │   │           └── [opens] (Total: 1)
│   │   │               └── [opens] (Total: 1)
│   │   │                   └── [delays product launch] (Total: 1)
│   │   ├── [excellence] (Total: 1)
│   │   │   └── [record quarterly revenue] (Total: 1)
│   │   ├── [disruptions] (Total: 1)
│   │   ├── [mixed results] (Total: 1)
│   │   ├── [schedules annual shareholder] (Total: 1)
│   │   ├── [reports unexpected decline in] (Total: 1)
│   │   ├── [withdraws] (Total: 1)
│   │   │   └── [host investor day] (Total: 1)
│   │   │       └── [misses] (Total: 1)
│   │   └── [buyback program] (Total: 1)
│   ├── [scheduled maintenance] (Total: 17)
│   │   ├── [secures] (Total: 2)
│   │   │   └── [buyback program] (Total: 1)
│   │   │       └── [secures] (Total: 1)
│   │   │           └── [regulatory review] (Total: 1)
│   │   ├── [decline in operating income] (Total: 1)
│   │   │   └── [secures] (Total: 1)
│   │   │       └── [enters joint venture] (Total: 1)
│   │   │           └── [breakthrough] (Total: 1)
│   │   ├── [beats analyst expectations] (Total: 1)
│   │   │   └── [delays product launch] (Total: 1)
│   │   │       └── [secures] (Total: 1)
│   │   │           └── [secures] (Total: 1)
│   │   ├── [steps down unexpectedly] (Total: 1)
│   │   │   └── [secures] (Total: 1)
│   │   ├── [class action] (Total: 1)
│   │   │   └── [revises long-term strategy] (Total: 1)
│   │   │       └── [breakthrough] (Total: 1)
│   │   │           └── [expands] (Total: 1)
│   │   ├── [regulatory review] (Total: 1)
│   │   │   └── [secures] (Total: 1)
│   │   ├── [excellence] (Total: 1)
│   │   │   └── [regulatory approval] (Total: 1)
│   │   ├── [expands] (Total: 1)
│   │   │   └── [signs multi-year partnership] (Total: 1)
│   │   │       └── [potential merger] (Total: 1)
│   │   ├── [explores strategic alternatives] (Total: 1)
│   │   ├── [drop] (Total: 1)
│   │   │   └── [record quarterly revenue] (Total: 1)
│   │   ├── [disruptions] (Total: 1)
│   │   └── [revises long-term strategy] (Total: 1)
│   │       └── [reports unexpected decline in] (Total: 1)
│   ├── [regulatory review] (Total: 16)
│   │   ├── [host investor day] (Total: 2)
│   │   │   ├── [reports unexpected decline in] (Total: 1)
│   │   │   └── [withdraws] (Total: 1)
│   │   ├── [loses key contract] (Total: 1)
│   │   │   └── [excellence] (Total: 1)
│   │   │       └── [launches] (Total: 1)
│   │   ├── [delays product launch] (Total: 1)
│   │   │   └── [routine patent applications] (Total: 1)
│   │   ├── [opens] (Total: 1)
│   │   ├── [buyback program] (Total: 1)
│   │   ├── [rising costs] (Total: 1)
│   │   ├── [breakthrough] (Total: 1)
│   │   │   └── [acquisition] (Total: 1)
│   │   ├── [improvement] (Total: 1)
│   │   ├── [publishes annual] (Total: 1)
│   │   │   └── [addresses investor concerns] (Total: 1)
│   │   ├── [recalls] (Total: 1)
│   │   │   └── [improvement] (Total: 1)
│   │   ├── [explores strategic alternatives] (Total: 1)
│   │   │   └── [mixed results] (Total: 1)
│   │   │       └── [new head] (Total: 1)
│   │   └── [secures] (Total: 1)
│   │       └── [misses] (Total: 1)
│   ├── [drop] (Total: 14)
│   │   ├── [secures] (Total: 2)
│   │   │   └── [secures] (Total: 1)
│   │   ├── [scheduled maintenance] (Total: 2)
│   │   │   └── [breakthrough] (Total: 1)
│   │   ├── [disruptions] (Total: 1)
│   │   │   └── [misses] (Total: 1)
│   │   ├── [drop] (Total: 1)
│   │   ├── [routine patent applications] (Total: 1)
│   │   └── [signs multi-year partnership] (Total: 1)
│   ├── [recalls] (Total: 13)
│   │   ├── [drop] (Total: 2)
│   │   │   └── [host investor day] (Total: 1)
│   │   ├── [mixed results] (Total: 1)
│   │   │   └── [scheduled maintenance] (Total: 1)
│   │   │       └── [expands] (Total: 1)
│   │   ├── [misses] (Total: 1)
│   │   ├── [regulatory review] (Total: 1)
│   │   │   └── [secures] (Total: 1)
│   │   ├── [secures] (Total: 1)
│   │   │   └── [expands] (Total: 1)
│   │   └── [revises long-term strategy] (Total: 1)
│   ├── [decline in operating income] (Total: 12)
│   │   ├── [secures] (Total: 4)
│   │   │   ├── [routine patent applications] (Total: 1)
│   │   │   │   └── [buyback program] (Total: 1)
│   │   │   │       └── [secures] (Total: 1)
│   │   │   │           └── [class action] (Total: 1)
│   │   │   ├── [secures] (Total: 1)
│   │   │   └── [revises long-term strategy] (Total: 1)
│   │   │       └── [explores strategic alternatives] (Total: 1)
│   │   ├── [host investor day] (Total: 1)
│   │   │   └── [secures] (Total: 1)
│   │   ├── [buyback program] (Total: 1)
│   │   ├── [regulatory review] (Total: 1)
│   │   ├── [class action] (Total: 1)
│   │   ├── [disruptions] (Total: 1)
│   │   │   └── [facility upgrade] (Total: 1)
│   │   └── [potential merger] (Total: 1)
│   ├── [strong demand] (Total: 11)
│   │   ├── [misses] (Total: 1)
│   │   ├── [secures] (Total: 1)
│   │   │   └── [facility upgrade] (Total: 1)
│   │   └── [delays product launch] (Total: 1)
│   ├── [delays product launch] (Total: 11)
│   │   ├── [host investor day] (Total: 1)
│   │   ├── [class action] (Total: 1)
│   │   ├── [rising costs] (Total: 1)
│   │   └── [present at] (Total: 1)
│   │       └── [scheduled maintenance] (Total: 1)
│   │           └── [opens] (Total: 1)
│   ├── [buyback program] (Total: 11)
│   │   ├── [excellence] (Total: 2)
│   │   ├── [enters joint venture] (Total: 1)
│   │   │   └── [excellence] (Total: 1)
│   │   ├── [revises long-term strategy] (Total: 1)
│   │   ├── [improvement] (Total: 1)
│   │   ├── [drop] (Total: 1)
│   │   │   └── [secures] (Total: 1)
│   │   └── [buyback program] (Total: 1)
│   │       └── [addresses investor concerns] (Total: 1)
│   ├── [new head] (Total: 11)
│   │   ├── [secures] (Total: 2)
│   │   │   └── [host investor day] (Total: 1)
│   │   │       └── [misses] (Total: 1)
│   │   ├── [present at] (Total: 2)
│   │   │   └── [secures] (Total: 1)
│   │   ├── [delays product launch] (Total: 1)
│   │   │   └── [expands] (Total: 1)
│   │   │       └── [host investor day] (Total: 1)
│   │   ├── [regulatory review] (Total: 1)
│   │   ├── [explores strategic alternatives] (Total: 1)
│   │   └── [class action] (Total: 1)
│   │       └── [regulatory review] (Total: 1)
│   ├── [excellence] (Total: 11)
│   │   ├── [secures] (Total: 2)
│   │   │   └── [revises long-term strategy] (Total: 1)
│   │   ├── [expands] (Total: 1)
│   │   ├── [buyback program] (Total: 1)
│   │   │   └── [secures] (Total: 1)
│   │   │       └── [acquisition] (Total: 1)
│   │   ├── [schedules annual shareholder] (Total: 1)
│   │   │   └── [restructuring] (Total: 1)
│   │   │       └── [present at] (Total: 1)
│   │   │           └── [breakthrough] (Total: 1)
│   │   │               └── [new head] (Total: 1)
│   │   ├── [regulatory review] (Total: 1)
│   │   │   └── [secures] (Total: 1)
│   │   │       └── [secures] (Total: 1)
│   │   │           └── [secures] (Total: 1)
│   │   ├── [breakthrough] (Total: 1)
│   │   │   └── [rising costs] (Total: 1)
│   │   └── [acquisition] (Total: 1)
│   │       └── [secures] (Total: 1)
│   │           └── [launches] (Total: 1)
│   ├── [rising costs] (Total: 10)
│   │   ├── [reports unexpected decline in] (Total: 1)
│   │   ├── [explores strategic alternatives] (Total: 1)
│   │   ├── [secures] (Total: 1)
│   │   │   └── [signs multi-year partnership] (Total: 1)
│   │   └── [regulatory review] (Total: 1)
│   │       └── [mixed results] (Total: 1)
│   ├── [explores strategic alternatives] (Total: 10)
│   │   ├── [buyback program] (Total: 1)
│   │   ├── [disruptions] (Total: 1)
│   │   ├── [scheduled maintenance] (Total: 1)
│   │   │   └── [steps down unexpectedly] (Total: 1)
│   │   ├── [acquisition] (Total: 1)
│   │   ├── [excellence] (Total: 1)
│   │   │   └── [strong demand] (Total: 1)
│   │   │       └── [addresses investor concerns] (Total: 1)
│   │   └── [secures] (Total: 1)
│   │       └── [regulatory approval] (Total: 1)
│   ├── [misses] (Total: 10)
│   │   ├── [secures] (Total: 2)
│   │   │   └── [secures] (Total: 1)
│   │   ├── [signs multi-year partnership] (Total: 2)
│   │   │   └── [regulatory approval] (Total: 1)
│   │   ├── [excellence] (Total: 1)
│   │   │   └── [breakthrough] (Total: 1)
│   │   ├── [strong demand] (Total: 1)
│   │   ├── [record quarterly revenue] (Total: 1)
│   │   ├── [delays product launch] (Total: 1)
│   │   └── [regulatory approval] (Total: 1)
│   ├── [revises long-term strategy] (Total: 9)
│   │   ├── [launches] (Total: 1)
│   │   │   └── [strong demand] (Total: 1)
│   │   ├── [secures] (Total: 1)
│   │   └── [regulatory review] (Total: 1)
│   ├── [host investor day] (Total: 9)
│   │   ├── [enters joint venture] (Total: 1)
│   │   ├── [scheduled maintenance] (Total: 1)
│   │   │   └── [scheduled maintenance] (Total: 1)
│   │   ├── [misses] (Total: 1)
│   │   ├── [delays product launch] (Total: 1)
│   │   │   └── [class action] (Total: 1)
│   │   └── [restructuring] (Total: 1)
│   ├── [record quarterly revenue] (Total: 9)
│   │   ├── [secures] (Total: 1)
│   │   │   └── [decline in operating income] (Total: 1)
│   │   │       └── [secures] (Total: 1)
│   │   ├── [expands] (Total: 1)
│   │   │   └── [expands] (Total: 1)
│   │   ├── [drop] (Total: 1)
│   │   │   └── [buyback program] (Total: 1)
│   │   ├── [rising costs] (Total: 1)
│   │   └── [decline in operating income] (Total: 1)
│   │       └── [secures] (Total: 1)
│   │           └── [regulatory approval] (Total: 1)
│   ├── [mixed results] (Total: 9)
│   │   ├── [potential merger] (Total: 1)
│   │   ├── [secures] (Total: 1)
│   │   ├── [new head] (Total: 1)
│   │   │   └── [raises full-year guidance] (Total: 1)
│   │   │       └── [secures] (Total: 1)
│   │   ├── [facility upgrade] (Total: 1)
│   │   │   └── [loses key contract] (Total: 1)
│   │   └── [expands] (Total: 1)
│   │       └── [secures] (Total: 1)
│   │           └── [acquisition] (Total: 1)
│   │               └── [regulatory approval] (Total: 1)
│   ├── [regulatory approval] (Total: 9)
│   │   ├── [improvement] (Total: 2)
│   │   │   └── [misses] (Total: 1)
│   │   │       └── [regulatory review] (Total: 1)
│   │   ├── [routine patent applications] (Total: 1)
│   │   │   └── [new head] (Total: 1)
│   │   ├── [expands] (Total: 1)
│   │   │   └── [acquisition] (Total: 1)
│   │   │       └── [secures] (Total: 1)
│   │   │           └── [revises long-term strategy] (Total: 1)
│   │   │               └── [explores strategic alternatives] (Total: 1)
│   │   ├── [new head] (Total: 1)
│   │   │   └── [signs multi-year partnership] (Total: 1)
│   │   │       └── [secures] (Total: 1)
│   │   └── [record quarterly revenue] (Total: 1)
│   ├── [launches] (Total: 9)
│   │   ├── [secures] (Total: 1)
│   │   ├── [host investor day] (Total: 1)
│   │   │   └── [acquisition] (Total: 1)
│   │   ├── [recalls] (Total: 1)
│   │   │   └── [drop] (Total: 1)
│   │   │       └── [beats analyst expectations] (Total: 1)
│   │   │           └── [buyback program] (Total: 1)
│   │   ├── [mixed results] (Total: 1)
│   │   │   └── [secures] (Total: 1)
│   │   ├── [explores strategic alternatives] (Total: 1)
│   │   └── [disruptions] (Total: 1)
│   │       └── [secures] (Total: 1)
│   ├── [addresses investor concerns] (Total: 8)
│   │   ├── [secures] (Total: 1)
│   │   ├── [acquisition] (Total: 1)
│   │   ├── [revises long-term strategy] (Total: 1)
│   │   └── [misses] (Total: 1)
│   │       └── [misses] (Total: 1)
│   ├── [routine patent applications] (Total: 8)
│   │   ├── [scheduled maintenance] (Total: 1)
│   │   │   └── [facility upgrade] (Total: 1)
│   │   ├── [breakthrough] (Total: 1)
│   │   │   └── [secures] (Total: 1)
│   │   │       └── [rising costs] (Total: 1)
│   │   ├── [class action] (Total: 1)
│   │   ├── [secures] (Total: 1)
│   │   │   └── [improvement] (Total: 1)
│   │   └── [mixed results] (Total: 1)
│   │       └── [disruptions] (Total: 1)
│   ├── [signs multi-year partnership] (Total: 8)
│   │   ├── [capital expenditure] (Total: 3)
│   │   │   ├── [loses key contract] (Total: 1)
│   │   │   └── [secures] (Total: 1)
│   │   ├── [routine patent applications] (Total: 1)
│   │   │   └── [confirms participation] (Total: 1)
│   │   └── [launches] (Total: 1)
│   │       └── [new head] (Total: 1)
│   ├── [disruptions] (Total: 8)
│   │   ├── [class action] (Total: 2)
│   │   │   ├── [confirms participation] (Total: 1)
│   │   │   └── [secures] (Total: 1)
│   │   ├── [breakthrough] (Total: 1)
│   │   │   └── [recalls] (Total: 1)
│   │   │       └── [secures] (Total: 1)
│   │   ├── [misses] (Total: 1)
│   │   └── [secures] (Total: 1)
│   ├── [opens] (Total: 8)
│   │   ├── [lowers full-year guidance] (Total: 1)
│   │   ├── [class action] (Total: 1)
│   │   │   └── [secures] (Total: 1)
│   │   ├── [scheduled maintenance] (Total: 1)
│   │   │   └── [secures] (Total: 1)
│   │   ├── [expands] (Total: 1)
│   │   │   └── [breakthrough] (Total: 1)
│   │   │       └── [breakthrough] (Total: 1)
│   │   ├── [rising costs] (Total: 1)
│   │   │   └── [lowers full-year guidance] (Total: 1)
│   │   │       └── [buyback program] (Total: 1)
│   │   └── [delays product launch] (Total: 1)
│   ├── [capital expenditure] (Total: 8)
│   │   ├── [routine patent applications] (Total: 1)
│   │   ├── [raises full-year guidance] (Total: 1)
│   │   ├── [secures] (Total: 1)
│   │   │   └── [withdraws] (Total: 1)
│   │   ├── [strong demand] (Total: 1)
│   │   │   └── [buyback program] (Total: 1)
│   │   │       └── [secures] (Total: 1)
│   │   ├── [improvement] (Total: 1)
│   │   │   └── [record quarterly revenue] (Total: 1)
│   │   └── [record quarterly revenue] (Total: 1)
│   │       └── [decline in operating income] (Total: 1)
│   ├── [expands] (Total: 8)
│   │   ├── [strong demand] (Total: 1)
│   │   │   └── [regulatory review] (Total: 1)
│   │   │       └── [rising costs] (Total: 1)
│   │   ├── [scheduled maintenance] (Total: 1)
│   │   ├── [drop] (Total: 1)
│   │   ├── [mixed results] (Total: 1)
│   │   │   └── [mixed results] (Total: 1)
│   │   ├── [restructuring] (Total: 1)
│   │   └── [steps down unexpectedly] (Total: 1)
│   │       └── [excellence] (Total: 1)
│   ├── [improvement] (Total: 8)
│   │   ├── [mixed results] (Total: 1)
│   │   ├── [buyback program] (Total: 1)
│   │   │   └── [expands] (Total: 1)
│   │   │       └── [secures] (Total: 1)
│   │   ├── [facility upgrade] (Total: 1)
│   │   ├── [signs multi-year partnership] (Total: 1)
│   │   ├── [secures] (Total: 1)
│   │   ├── [addresses investor concerns] (Total: 1)
│   │   │   └── [publishes annual] (Total: 1)
│   │   │       └── [drop] (Total: 1)
│   │   │           └── [host investor day] (Total: 1)
│   │   │               └── [regulatory approval] (Total: 1)
│   │   └── [reports unexpected decline in] (Total: 1)
│   ├── [class action] (Total: 7)
│   │   ├── [routine patent applications] (Total: 1)
│   │   ├── [expands] (Total: 1)
│   │   ├── [regulatory approval] (Total: 1)
│   │   │   └── [withdraws] (Total: 1)
│   │   │       └── [restructuring] (Total: 1)
│   │   └── [withdraws] (Total: 1)
│   │       └── [regulatory review] (Total: 1)
│   │           └── [new head] (Total: 1)
│   │               └── [drop] (Total: 1)
│   ├── [confirms participation] (Total: 7)
│   │   ├── [secures] (Total: 2)
│   │   │   └── [withdraws] (Total: 1)
│   │   │       └── [schedules annual shareholder] (Total: 1)
│   │   ├── [loses key contract] (Total: 1)
│   │   │   └── [confirms participation] (Total: 1)
│   │   └── [regulatory approval] (Total: 1)

In [15]:
def export_nested_patterns(frequency_df, filename="event_tree.txt"):
    # 1. Build the Tree (Same logic as before)
    tree = {}
    for _, row in frequency_df.iterrows():
        sequence = row['encoded_keywords']
        freq = row['frequency']
        if not sequence: continue
        current_node = tree
        for event in sequence:
            if event not in current_node:
                current_node[event] = {'_count': 0, 'children': {}}
            current_node[event]['_count'] += freq
            current_node = current_node[event]['children']

    # 2. Recursive function to WRITE to file instead of printing
    def write_tree(node, file, prefix=""):
        sorted_branches = sorted(node.items(), key=lambda item: item[1]['_count'], reverse=True)
        for i, (event, data) in enumerate(sorted_branches):
            is_last = (i == len(sorted_branches) - 1)
            count = data['_count']
            branch_char = "└── " if is_last else "├── "
            
            # Write to the file
            file.write(f"{prefix}{branch_char}[{event}] (Total: {count})\n")
            
            next_prefix = prefix + ("    " if is_last else "│   ")
            write_tree(data['children'], file, next_prefix)

    # Open the file and start writing
    with open(filename, 'w') as f:
        f.write("--- Nested Event Sequences ---\n\n")
        write_tree(tree, f)
    
    print(f"Success! Tree saved to {filename}. Open it in a text editor with Word Wrap disabled.")

# Run it:
# export_nested_patterns(frequency_df, "my_session_tree.txt")

In [16]:
export_nested_patterns(frequency_df, "headlines_tree_seen_test.txt")

Success! Tree saved to headlines_tree_seen_test.txt. Open it in a text editor with Word Wrap disabled.

In [17]:
DATA_DIR = "../data"

bars_seen_train         = pd.read_parquet(os.path.join(DATA_DIR, "bars_seen_train.parquet"), engine="fastparquet")
bars_unseen_train       = pd.read_parquet(os.path.join(DATA_DIR, "bars_unseen_train.parquet"), engine="fastparquet")
bars_seen_public_test   = pd.read_parquet(os.path.join(DATA_DIR, "bars_seen_public_test.parquet"), engine="fastparquet")
bars_seen_private_test  = pd.read_parquet(os.path.join(DATA_DIR, "bars_seen_private_test.parquet"), engine="fastparquet")

headlines_seen_train        = pd.read_parquet(os.path.join(DATA_DIR, "headlines_seen_train.parquet"), engine="fastparquet")
headlines_unseen_train      = pd.read_parquet(os.path.join(DATA_DIR, "headlines_unseen_train.parquet"), engine="fastparquet")
headlines_seen_public_test  = pd.read_parquet(os.path.join(DATA_DIR, "headlines_seen_public_test.parquet"), engine="fastparquet")
headlines_seen_private_test = pd.read_parquet(os.path.join(DATA_DIR, "headlines_seen_private_test.parquet"), engine="fastparquet")

print("bars_seen_train:",         bars_seen_train.shape)
print("bars_unseen_train:",       bars_unseen_train.shape)
print("bars_seen_public_test:",   bars_seen_public_test.shape)
print("bars_seen_private_test:",  bars_seen_private_test.shape)
print("headlines_seen_train:",        headlines_seen_train.shape)
print("headlines_unseen_train:",      headlines_unseen_train.shape)
print("headlines_seen_public_test:",  headlines_seen_public_test.shape)
print("headlines_seen_private_test:", headlines_seen_private_test.shape)

bars_seen_train: (50000, 6)
bars_unseen_train: (50000, 6)
bars_seen_public_test: (500000, 6)
bars_seen_private_test: (500000, 6)
headlines_seen_train: (9740, 3)
headlines_unseen_train: (7631, 3)
headlines_seen_public_test: (99308, 3)
headlines_seen_private_test: (99148, 3)

In [18]:
combined_train  = pd.concat([headlines_seen_train, headlines_unseen_train]).sort_values(by=['session', 'bar_ix'])

In [19]:
combined_train.head(50)

    session                                           headline  bar_ix
0         0  Relvos Biosciences opens new office in Southea...       6
1         0  Orevex Renewables secures $500M contract with ...      12
2         0  Relvos Biosciences names new head of precision...      14
3         0  Calvis Sciences secures $650M contract with a ...      20
4         0  Yorvov Pharmaceuticals secures $180M contract ...      22
5         0  Relvos Biosciences reports 3% decline in opera...      26
6         0  Relvos Biosciences secures $320M contract with...      26
7         0  Calvis Sciences expands operations into Asia P...      33
8         0  Yorvov Pharmaceuticals sees mixed results in s...      44
9         0  Orevex Renewables secures $650M contract with ...      47
10        0  Orevex Renewables faces class action over auto...      48
11        0  Orevex Renewables begins scheduled maintenance...      51
12        0  Yorvov Pharmaceuticals secures $120M contract ...      53
13        0  Relvos Biosciences secures $800M contract with...      55
14        0  Calvis Sciences names new head of data analyti...      59
15        0  Calvis Sciences sees mixed results in wireless...      62
16        0  Yorvov Pharmaceuticals sees 20% margin improve...      68
17        0  Relvos Biosciences to present at Tech Leadersh...      68
18        0  Yorvov Pharmaceuticals faces class action over...      71
19        0  Orevex Renewables launches next-generation sup...      74
20        0  Calvis Sciences begins scheduled maintenance o...      82
21        0  Orevex Renewables secures $120M contract with ...      85
22        1  Strynal Industries reports 15% decline in oper...       3
23        1  Jorvis Fuels reports record quarterly revenue,...       5
24        1  Zrovex Industries loses key contract in Asia P...       6
25        1  Strynal Industries reports 20% increase in cus...       6
26        1  Zrovex Industries reports strong demand in Lat...      11
27        1  Jorvis Fuels secures $400M contract with an in...      12
28        1  Halvav Brands sees mixed results in wireless c...      14
29        1  Zrovex Industries completes strategic acquisit...      19
30        1  Jorvis Fuels sees 12% margin improvement in la...      20
31        1  Zrovex Industries faces class action over digi...      26
32        1  Zrovex Industries reports rising costs pressur...      29
33        1  Jorvis Fuels secures $75M contract with a mult...      29
34        1  Halvav Brands reports rising costs pressuring ...      33
35        1  Zrovex Industries sees 25% drop in new custome...      44
36        1  Jorvis Fuels names new head of process automat...      45
37        1  Jorvis Fuels recalls products in digital payme...      49
38        1  Halvav Brands files routine patent application...      51
39        1  Zrovex Industries delays product launch in aut...      63
40        1  Strynal Industries announces breakthrough in e...      66
41        1  Jorvis Fuels sees 12% drop in new customer ord...      70
42        1  Strynal Industries secures $320M contract with...      76
43        1  Halvav Brands names new head of renewable stor...      77
44        1  Zrovex Industries reports rising costs pressur...      81
45        1  Strynal Industries wins industry award for exc...      88
46        1  Strynal Industries warns of supply chain disru...      89
47        2  Kelvik Power secures $800M contract with a lea...       3
48        2  Zelval Energy to host investor day focused on ...      30
49        2  Zelval Energy misses quarterly revenue estimat...      31

In [25]:
train_headlines_per_company_session = build_company_session_logs(combined_train)

In [26]:
train_headlines_per_company_session['encoded_keywords'] = train_headlines_per_company_session['all_headlines'].apply(replace_headlines_with_keywords)

In [27]:
unique_train_tuples = train_headlines_per_company_session['encoded_keywords'].apply(tuple).unique()

# 2. Convert them back to lists for easy reading
train_all_unique_patterns = [list(pattern) for pattern in unique_train_tuples]

print(f"Total unique patterns found: {len(all_unique_patterns)}\n")

# Print them all out
for pattern in train_all_unique_patterns:
    print(pattern)

Total unique patterns found: 2458

['secures', 'expands', 'new head', 'mixed results', 'scheduled maintenance']
['secures', 'secures', 'class action', 'scheduled maintenance', 'launches', 'secures']
['opens', 'new head', 'decline in operating income', 'secures', 'secures', 'present at']
['secures', 'mixed results', 'secures', 'improvement', 'class action']
['mixed results', 'rising costs', 'routine patent applications', 'new head']
['record quarterly revenue', 'secures', 'improvement', 'secures', 'new head', 'recalls', 'drop']
['decline in operating income', 'acquisition', 'breakthrough', 'secures', 'excellence', 'disruptions']
['loses key contract', 'strong demand', 'acquisition', 'class action', 'rising costs', 'drop', 'delays product launch', 'rising costs']
['secures', 'withdraws', 'secures', 'launches', 'recalls', 'misses', 'opens', 'class action']
['new head', 'breakthrough', 'improvement', 'expands']
['mixed results', 'secures', 'scheduled maintenance', 'drop', 'class action', 'excellence']
['host investor day', 'misses', 'launches', 'addresses investor concerns']
['withdraws', 'scheduled maintenance', 'host investor day']
['explores strategic alternatives', 'secures', 'strong demand', 'acquisition', 'breakthrough', 'secures', 'signs multi-year partnership']
['facility upgrade', 'steps down unexpectedly', 'routine patent applications', 'loses key contract', 'regulatory review', 'acquisition', 'revises long-term strategy']
['drop', 'revises long-term strategy', 'secures', 'secures']
['withdraws', 'acquisition', 'enters joint venture']
['rising costs', 'improvement', 'explores strategic alternatives']
['new head', 'buyback program', 'disruptions', 'improvement']
['secures', 'launches', 'explores strategic alternatives', 'improvement', 'acquisition', 'excellence']
['decline in operating income', 'buyback program', 'routine patent applications', 'record quarterly revenue', 'delays product launch', 'reports unexpected decline in', 'confirms participation']
['drop', 'secures', 'rising costs']
['new head', 'present at', 'secures']
['capital expenditure', 'delays product launch']
['secures', 'facility upgrade', 'schedules annual shareholder', 'class action', 'secures', 'acquisition', 'regulatory review']
['capital expenditure', 'acquisition', 'class action', 'signs multi-year partnership']
['regulatory review', 'secures', 'secures', 'regulatory milestone']
['acquisition', 'acquisition', 'reports unexpected decline in', 'decline in operating income']
['buyback program', 'scheduled maintenance']
['confirms participation', 'secures', 'rising costs', 'revises long-term strategy']
['improvement', 'scheduled maintenance', 'record quarterly revenue', 'recalls', 'expands', 'breakthrough', 'regulatory review']
['routine patent applications', 'secures', 'revises long-term strategy', 'expands']
['improvement', 'capital expenditure', 'explores strategic alternatives', 'disruptions', 'reports unexpected decline in', 'recalls']
['strong demand', 'launches', 'secures', 'new head', 'secures']
['loses key contract']
['mixed results']
['drop', 'excellence', 'misses', 'secures', 'rising costs']
['scheduled maintenance', 'disruptions']
['scheduled maintenance', 'loses key contract', 'new head', 'disruptions', 'secures']
['routine patent applications', 'new head', 'launches', 'mixed results']
['restructuring', 'delays product launch', 'facility upgrade', 'routine patent applications', 'secures', 'strong demand', 'rising costs', 'class action']
['regulatory approval', 'secures', 'capital expenditure']
['secures', 'host investor day', 'misses', 'scheduled maintenance', 'signs multi-year partnership', 'present at']
['explores strategic alternatives', 'recalls', 'acquisition', 'acquisition', 'rising costs', 'opens', 'launches', 'enters joint venture']
['regulatory review', 'record quarterly revenue', 'recalls']
['revises long-term strategy']
['steps down unexpectedly', 'excellence', 'expands']
['class action', 'delays product launch', 'acquisition', 'excellence']
['secures', 'regulatory approval', 'expands', 'acquisition', 'secures', 'revises long-term strategy', 'explores strategic alternatives']
['loses key contract', 'record quarterly revenue']
['host investor day', 'misses', 'secures', 'secures']
['enters joint venture', 'breakthrough', 'withdraws']
['breakthrough', 'excellence', 'enters joint venture']
['addresses investor concerns']
['host investor day', 'explores strategic alternatives', 'reports unexpected decline in', 'launches']
['mixed results', 'secures', 'misses', 'loses key contract', 'capital expenditure', 'new head', 'capital expenditure', 'new head', 'delays product launch']
['secures', 'reports unexpected decline in', 'secures', 'expands', 'delays product launch', 'decline in operating income', 'regulatory review']
['explores strategic alternatives', 'decline in operating income']
['secures', 'secures', 'regulatory approval', 'restructuring', 'secures', 'decline in operating income']
['excellence', 'secures', 'lowers full-year guidance']
['revises long-term strategy', 'acquisition', 'improvement', 'secures', 'decline in operating income', 'decline in operating income', 'opens']
['expands', 'secures', 'addresses investor concerns', 'enters joint venture', 'secures']
['secures', 'confirms participation']
['opens', 'launches']
['revises long-term strategy', 'routine patent applications', 'excellence', 'misses', 'opens', 'drop']
['secures', 'decline in operating income', 'secures', 'revises long-term strategy', 'explores strategic alternatives']
['regulatory approval', 'scheduled maintenance', 'signs multi-year partnership']
['routine patent applications', 'recalls', 'revises long-term strategy']
['breakthrough', 'disruptions', 'recalls']
['revises long-term strategy', 'record quarterly revenue', 'buyback program']
['loses key contract', 'scheduled maintenance']
['regulatory milestone', 'class action', 'explores strategic alternatives', 'scheduled maintenance']
['mixed results', 'new head', 'misses', 'excellence', 'withdraws']
['delays product launch', 'launches', 'withdraws']
['recalls', 'explores strategic alternatives', 'expands', 'expands', 'breakthrough', 'recalls']
['disruptions', 'acquisition', 'explores strategic alternatives', 'regulatory approval', 'buyback program', 'expands']
['expands', 'secures', 'rising costs', 'delays product launch']
['acquisition', 'host investor day', 'opens', 'secures', 'reports unexpected decline in', 'regulatory review']
['withdraws', 'withdraws', 'explores strategic alternatives', 'secures']
['new head', 'opens', 'secures', 'acquisition', 'record quarterly revenue']
['excellence', 'secures', 'secures', 'record quarterly revenue', 'present at', 'host investor day', 'secures']
['misses', 'secures', 'launches', 'new head', 'secures']
['recalls', 'new head', 'decline in operating income']
['expands']
['explores strategic alternatives', 'regulatory approval', 'signs multi-year partnership', 'secures', 'secures', 'signs multi-year partnership']
['host investor day', 'loses key contract', 'acquisition', 'breakthrough', 'buyback program', 'strong demand', 'drop', 'delays product launch']
['routine patent applications', 'buyback program', 'decline in operating income', 'lowers full-year guidance', 'secures', 'secures', 'publishes annual', 'acquisition']
['reports unexpected decline in', 'host investor day', 'breakthrough']
['acquisition', 'scheduled maintenance', 'confirms participation', 'secures', 'withdraws', 'secures']
['delays product launch', 'signs multi-year partnership']
['secures', 'secures']
['new head', 'explores strategic alternatives', 'scheduled maintenance', 'new head', 'withdraws']
['delays product launch', 'regulatory review', 'misses', 'secures', 'explores strategic alternatives', 'withdraws', 'enters joint venture']
['secures', 'improvement', 'secures', 'delays product launch', 'secures', 'revises long-term strategy']
['explores strategic alternatives', 'record quarterly revenue', 'explores strategic alternatives', 'breakthrough', 'explores strategic alternatives', 'secures', 'confirms participation']
['host investor day', 'recalls', 'record quarterly revenue']
['acquisition', 'new head', 'delays product launch', 'steps down unexpectedly']
['facility upgrade', 'improvement', 'withdraws', 'misses', 'secures', 'delays product launch', 'secures', 'withdraws']
['secures', 'decline in operating income', 'secures', 'secures', 'class action', 'present at', 'disruptions']
['delays product launch', 'facility upgrade']
['regulatory review', 'routine patent applications', 'record quarterly revenue', 'secures']
['buyback program', 'facility upgrade', 'routine patent applications', 'secures', 'regulatory approval', 'buyback program']
['excellence', 'secures', 'routine patent applications', 'regulatory review', 'launches']
['beats analyst expectations', 'improvement']
['confirms participation', 'acquisition', 'secures', 'regulatory review', 'misses', 'facility upgrade', 'mixed results']
['secures', 'class action', 'secures', 'buyback program']
['record quarterly revenue', 'host investor day', 'steps down unexpectedly', 'capital expenditure']
['acquisition', 'secures', 'present at', 'revises long-term strategy']
['regulatory approval', 'strong demand', 'steps down unexpectedly', 'secures', 'acquisition', 'delays product launch', 'drop']
['enters joint venture', 'secures', 'decline in operating income', 'secures']
['secures', 'secures', 'scheduled maintenance', 'breakthrough', 'new head', 'facility upgrade', 'regulatory approval']
['scheduled maintenance', 'explores strategic alternatives', 'secures']
['rising costs', 'acquisition', 'explores strategic alternatives', 'mixed results', 'opens']
['enters joint venture', 'scheduled maintenance', 'secures', 'secures']
['secures', 'strong demand', 'confirms participation', 'launches']
['signs multi-year partnership', 'regulatory approval', 'secures']
['secures', 'misses', 'regulatory approval', 'secures']
['drop', 'capital expenditure', 'loses key contract', 'scheduled maintenance', 'restructuring', 'class action']
['expands', 'loses key contract', 'withdraws']
['decline in operating income', 'mixed results', 'reports unexpected decline in', 'secures', 'withdraws', 'disruptions']
['rising costs', 'improvement', 'secures', 'excellence']
['secures', 'host investor day', 'decline in operating income', 'withdraws', 'acquisition', 'acquisition']
['record quarterly revenue', 'excellence']
['secures', 'addresses investor concerns']
['host investor day', 'rising costs', 'host investor day']
['acquisition', 'secures', 'scheduled maintenance', 'recalls', 'confirms participation', 'rising costs', 'record quarterly revenue']
['confirms participation', 'explores strategic alternatives', 'explores strategic alternatives']
['revises long-term strategy', 'breakthrough']
['signs multi-year partnership', 'buyback program', 'drop']
['breakthrough', 'drop', 'mixed results']
['misses', 'withdraws', 'confirms participation', 'secures']
['new head', 'buyback program', 'scheduled maintenance', 'signs multi-year partnership']
['decline in operating income', 'withdraws', 'secures', 'excellence', 'mixed results', 'new head']
['class action', 'facility upgrade', 'new head', 'secures', 'drop', 'class action']
['secures', 'delays product launch', 'launches', 'class action']
['secures', 'routine patent applications', 'strong demand', 'loses key contract', 'decline in operating income', 'secures']
['acquisition', 'withdraws', 'disruptions', 'acquisition']
['secures', 'excellence', 'acquisition', 'secures', 'launches', 'launches']
['regulatory approval', 'loses key contract', 'rising costs', 'withdraws']
['class action', 'scheduled maintenance', 'buyback program']
['routine patent applications', 'misses']
['facility upgrade', 'secures']
['recalls']
['acquisition', 'launches', 'launches', 'delays product launch']
['secures', 'misses', 'secures', 'explores strategic alternatives', 'record quarterly revenue']
['mixed results', 'launches', 'secures']
['improvement', 'withdraws', 'record quarterly revenue', 'improvement', 'facility upgrade']
['confirms participation', 'addresses investor concerns', 'secures', 'loses key contract', 'misses']
['present at', 'improvement']
['record quarterly revenue', 'facility upgrade', 'routine patent applications', 'regulatory approval', 'facility upgrade', 'secures']
['drop', 'secures', 'withdraws', 'misses']
['secures']
['new head', 'withdraws', 'regulatory approval', 'opens']
['delays product launch', 'reports unexpected decline in', 'improvement', 'record quarterly revenue', 'loses key contract', 'class action', 'buyback program']
['excellence', 'decline in operating income', 'regulatory approval', 'explores strategic alternatives', 'breakthrough', 'delays product launch']
['steps down unexpectedly', 'routine patent applications', 'revises long-term strategy', 'disruptions']
['acquisition', 'secures', 'drop', 'expands', 'revises long-term strategy', 'opens', 'rising costs']
['recalls', 'delays product launch']
['drop', 'buyback program', 'routine patent applications', 'secures', 'secures']
['secures', 'secures', 'rising costs', 'decline in operating income', 'drop']
['scheduled maintenance', 'present at']
['secures', 'rising costs', 'secures', 'secures']
['lowers full-year guidance', 'secures', 'regulatory review', 'improvement', 'launches', 'excellence']
['signs multi-year partnership', 'rising costs']
['buyback program', 'capital expenditure', 'withdraws', 'excellence', 'acquisition', 'secures', 'mixed results', 'strong demand', 'new head', 'reports unexpected decline in']
['drop', 'routine patent applications', 'revises long-term strategy', 'present at', 'steps down unexpectedly']
['delays product launch', 'improvement']
['delays product launch', 'secures', 'lowers full-year guidance', 'decline in operating income', 'secures', 'secures']
['secures', 'secures', 'capital expenditure', 'buyback program']
['recalls', 'host investor day', 'decline in operating income', 'acquisition', 'revises long-term strategy', 'secures']
['secures', 'decline in operating income']
['new head', 'host investor day', 'acquisition', 'mixed results', 'routine patent applications', 'disruptions', 'decline in operating income']
['rising costs', 'withdraws', 'secures']
['buyback program']
['loses key contract', 'regulatory review', 'regulatory review', 'secures']
['routine patent applications', 'secures', 'launches', 'secures', 'steps down unexpectedly']
['new head', 'misses', 'scheduled maintenance', 'launches', 'secures']
['revises long-term strategy', 'improvement', 'disruptions', 'recalls', 'launches', 'expands']
['host investor day', 'host investor day', 'restructuring', 'restructuring', 'secures', 'acquisition']
['loses key contract', 'secures', 'rising costs', 'acquisition', 'misses', 'misses']
['recalls', 'mixed results', 'secures', 'expands']
['host investor day', 'decline in operating income', 'strong demand', 'recalls']
['signs multi-year partnership', 'buyback program', 'new head', 'misses', 'regulatory review']
['present at', 'rising costs', 'regulatory approval']
['secures', 'reports unexpected decline in', 'recalls', 'rising costs']
['revises long-term strategy', 'delays product launch']
['decline in operating income', 'drop', 'decline in operating income', 'opens', 'enters joint venture', 'strong demand']
['enters joint venture', 'decline in operating income', 'secures', 'excellence']
['buyback program', 'launches', 'expands', 'rising costs']
['secures', 'revises long-term strategy', 'new head']
['host investor day', 'class action', 'regulatory review', 'strong demand', 'secures', 'acquisition', 'loses key contract']
['addresses investor concerns', 'class action', 'capital expenditure', 'loses key contract']
['delays product launch', 'confirms participation']
['revises long-term strategy', 'loses key contract']
['secures', 'secures', 'routine patent applications', 'opens', 'acquisition', 'regulatory approval']
['secures', 'excellence', 'drop', 'scheduled maintenance']
['drop', 'launches', 'scheduled maintenance', 'withdraws', 'secures', 'excellence', 'reports unexpected decline in']
['strong demand', 'decline in operating income']
['secures', 'delays product launch', 'buyback program', 'reports unexpected decline in', 'expands']
['delays product launch', 'enters joint venture']
['class action', 'strong demand', 'new head', 'addresses investor concerns', 'enters joint venture', 'opens', 'record quarterly revenue', 'class action', 'mixed results']
['class action']
['secures', 'decline in operating income', 'beats analyst expectations', 'routine patent applications']
['breakthrough', 'revises long-term strategy']
['signs multi-year partnership', 'rising costs', 'secures', 'loses key contract']
['steps down unexpectedly', 'scheduled maintenance', 'facility upgrade']
['strong demand', 'strong demand', 'confirms participation', 'secures', 'new head', 'opens']
['loses key contract', 'present at', 'addresses investor concerns', 'excellence']
['secures', 'misses', 'signs multi-year partnership', 'capital expenditure']
['class action', 'confirms participation', 'regulatory approval']
['routine patent applications', 'secures']
['expands', 'secures', 'mixed results', 'improvement']
['mixed results', 'secures', 'mixed results', 'host investor day', 'secures', 'signs multi-year partnership']
['record quarterly revenue', 'excellence', 'confirms participation', 'host investor day', 'withdraws']
['addresses investor concerns', 'facility upgrade', 'buyback program', 'new head']
['breakthrough', 'secures', 'routine patent applications', 'host investor day', 'secures']
['decline in operating income', 'capital expenditure', 'record quarterly revenue', 'recalls', 'revises long-term strategy', 'secures', 'signs multi-year partnership']
['explores strategic alternatives', 'regulatory review', 'excellence', 'acquisition', 'mixed results']
['buyback program', 'mixed results', 'capital expenditure', 'record quarterly revenue', 'host investor day', 'steps down unexpectedly', 'mixed results', 'revises long-term strategy']
['scheduled maintenance', 'decline in operating income', 'scheduled maintenance', 'regulatory approval', 'class action', 'rising costs', 'signs multi-year partnership', 'disruptions', 'regulatory approval', 'secures']
['acquisition', 'secures', 'class action', 'buyback program', 'capital expenditure']
['regulatory approval', 'secures', 'schedules annual shareholder']
['publishes annual', 'secures', 'record quarterly revenue', 'secures', 'launches']
['recalls', 'disruptions', 'secures', 'expands']
['class action', 'delays product launch', 'acquisition', 'revises long-term strategy', 'excellence', 'decline in operating income', 'launches', 'launches', 'buyback program', 'mixed results', 'record quarterly revenue', 'routine patent applications']
['present at', 'opens', 'expands', 'regulatory approval', 'breakthrough']
['host investor day', 'scheduled maintenance', 'strong demand', 'excellence']
['host investor day', 'mixed results', 'regulatory approval']
['launches', 'secures', 'disruptions']
['class action', 'excellence', 'excellence']
['enters joint venture', 'secures', 'improvement', 'launches', 'improvement', 'acquisition', 'beats analyst expectations']
['scheduled maintenance', 'secures', 'improvement', 'improvement', 'new head', 'steps down unexpectedly', 'rising costs', 'excellence']
['launches', 'loses key contract']
['mixed results', 'routine patent applications']
['secures', 'secures', 'launches', 'secures']
['revises long-term strategy', 'loses key contract', 'class action']
['reports unexpected decline in', 'routine patent applications', 'secures', 'excellence', 'acquisition']
['acquisition', 'secures', 'acquisition', 'secures', 'recalls']
['new head', 'secures', 'record quarterly revenue', 'routine patent applications', 'loses key contract', 'scheduled maintenance']

In [23]:
train_frequency_df = train_headlines_per_company_session['encoded_keywords'].apply(tuple).value_counts().reset_index()
train_frequency_df.columns = ['encoded_keywords', 'frequency']

# 3. Convert the tuples back to lists for a cleaner look
train_frequency_df['encoded_keywords'] = train_frequency_df['encoded_keywords'].apply(list)

In [24]:
train_frequency_df[train_frequency_df["frequency"]>5]

                         encoded_keywords  frequency
0                               [secures]        132
1                           [acquisition]         45
2            [revises long-term strategy]         33
3                 [scheduled maintenance]         31
4                         [mixed results]         27
5                     [regulatory review]         24
6                          [class action]         23
7                            [excellence]         23
8                 [delays product launch]         23
9                      [secures, secures]         22
10                         [rising costs]         20
11                               [misses]         20
12                             [launches]         20
13                              [recalls]         20
14                          [disruptions]         20
15                              [expands]         20
16                                 [drop]         20
17                         [breakthrough]         19
18                             [new head]         19
19                    [host investor day]         19
20         [signs multi-year partnership]         18
21          [routine patent applications]         18
22                 [enters joint venture]         18
23      [explores strategic alternatives]         17
24             [record quarterly revenue]         17
25                          [improvement]         16
26                  [regulatory approval]         16
27                        [strong demand]         15
28          [decline in operating income]         14
29                            [withdraws]         14
30                   [loses key contract]         14
31               [confirms participation]         14
32                           [present at]         14
33                      [buyback program]         14
34        [reports unexpected decline in]         13
35                  [capital expenditure]         12
36                                [opens]         12
37                     [facility upgrade]         12
38                 [secures, acquisition]         11
39              [steps down unexpectedly]         10
40                 [acquisition, secures]          8
41               [secures, strong demand]          8
42          [addresses investor concerns]          8
43       [secures, delays product launch]          7
44                        [secures, drop]          6
45  [secures, revises long-term strategy]          6
46                    [new head, secures]          6
47                [secures, rising costs]          6
48                     [secures, recalls]          6